# -*- coding: utf-8 -*-
"""SayiTahminOyunu.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHc0vdJ1vitrvtPBfrD3FoRnNRBAEL9P

***SAYI TAHMİN OYUNU***
"""

import random

sayi = random.randint(1,50)
hak = 5
while hak>0:
  hak-=1
  tahmin = int(input("Tahmininiz:"))
  if (tahmin == sayi):
    print("Tebrikler doğru tahmin ettiniz.")
    break
  elif tahmin>sayi:
    print(f"Aşağı.Kalan hakkınız:{hak}")
  elif tahmin<sayi:
    print(f"Yukarı.Kalan hakkınız:{hak}")
  if hak == 0:
    print("Hakkınız bitti.Sayı:",sayi)

